# Item Vector Building with SBERT

Notebook này khởi tạo và chạy pipeline để extract semantic vector (SBERT) cho Content-Based Filtering thông qua file Parquet, và ghi ra file `memmap` như kế hoạch thực thi.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import sys
import os
import numpy as np
import pandas as pd

# Add scripts to sys.path
%pip install faiss-cpu
BASEDIR = '/content/drive/My Drive/Thesis/book_recsys'
sys.path.append(os.path.abspath(BASEDIR))
from scripts.item_vector_builder import ItemVectorBuilder
from scripts.faiss_builder import FaissBuilder

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.13.2)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.1)

In [4]:
# Định nghĩa constants
VERSION = "v1"
_PROC              = f'{BASEDIR}/data/processed_2/'
INPUT_PQ           = f'{_PROC}books_cleaned.parquet'#f'{_PROC}books_filtered.parquet'

_OUTDIR            = f'{_PROC}model_{VERSION}/'
os.makedirs(_OUTDIR, exist_ok=True)

OUTPUT_MATRIX  = f'{_OUTDIR}cb_sbert_matrix_v2.npy'
OUTPUT_INDEX       = f'{_OUTDIR}cb_sbert_book_index.csv'
OUTPUT_CKPT        = f'{_OUTDIR}cb_sbert_progress.json'
MODEL_NAME = 'sentence-transformers/all-MiniLM-L6-v2'


CHUNK_SIZE = 50000
ENCODE_BATCH = 256
MAX_DESC_CHARS = 300

builder = ItemVectorBuilder(
    input_parquet=INPUT_PQ,
    output_matrix_path=OUTPUT_MATRIX,
    output_index_path=OUTPUT_INDEX,
    model_name=MODEL_NAME,
    chunk_size=CHUNK_SIZE,
    encode_batch_size=ENCODE_BATCH,
    max_desc_chars=MAX_DESC_CHARS,
    device=None
)

In [6]:
# Kích hoạt tiến trình map vectors
builder.build()

Starting vector build from /content/drive/My Drive/Thesis/book_recsys/data/processed_2/books_cleaned.parquet
Total rows in dataset: 1173713
Loading SentenceTransformer model 'sentence-transformers/all-MiniLM-L6-v2' on device: cuda...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

/content/drive/My Drive/Thesis/book_recsys/scripts/item_vector_builder.py:270: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  return self.model.get_sentence_embedding_dimension()

Initializing NPY memmap target: shape=1173713x384

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 50000/1173713 - Current RAM: 2513.4 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 100000/1173713 - Current RAM: 2729.9 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 150000/1173713 - Current RAM: 2865.3 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 200000/1173713 - Current RAM: 2954.1 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 250000/1173713 - Current RAM: 3022.2 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 300000/1173713 - Current RAM: 3087.9 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 350000/1173713 - Current RAM: 3176.0 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 400000/1173713 - Current RAM: 3262.9 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 450000/1173713 - Current RAM: 3337.2 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 500000/1173713 - Current RAM: 3419.1 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 550000/1173713 - Current RAM: 3492.2 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 600000/1173713 - Current RAM: 3557.2 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 650000/1173713 - Current RAM: 3637.1 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 700000/1173713 - Current RAM: 3710.8 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 750000/1173713 - Current RAM: 3793.6 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 800000/1173713 - Current RAM: 3866.8 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 850000/1173713 - Current RAM: 3941.2 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 900000/1173713 - Current RAM: 4014.3 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 950000/1173713 - Current RAM: 4087.6 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 1000000/1173713 - Current RAM: 4161.1 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 1050000/1173713 - Current RAM: 3753.5 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 1100000/1173713 - Current RAM: 3797.0 MB

Batches:   0%|          | 0/196 [00:00<?, ?it/s]

Processed chunks: 1150000/1173713 - Current RAM: 3889.4 MB

Batches:   0%|          | 0/93 [00:00<?, ?it/s]

Processed chunks: 1173713/1173713 - Current RAM: 3891.3 MB
====== BUILD SUMMARY ======
Total Rows Processed: 1173713
Output Matrix path: /content/drive/My Drive/Thesis/book_recsys/data/processed_2/model_v1/cb_sbert_matrix_v2.npy
Output Index path: /content/drive/My Drive/Thesis/book_recsys/data/processed_2/model_v1/cb_sbert_book_index.csv
Peak Runtime RAM Usage: 4161.1 MB
Index-Matrix alignment: VERIFIED
===========================

In [5]:
# --- CELL BỔ SUNG: VÉT CỨU HỘ HOẶC BUILD ĐỘC LẬP FILE INDEX CSV ---
# Chạy cell này sẽ sử dụng hàm độc lập build_index_csv() ta vừa xây trong Class.
# Nó đọc trực tiếp từ Parquet theo đúng thứ tự mảng gốc rồi dump chốt 1 lần xuống Drive.

try:
    print("Tiến hành chạy hàm vét CSV Index từ Parquet gốc...")
    id_map_df = builder.build_index_csv()

    # In ra một số dòng để bạn check thứ tự row_idx và book_id
    print("\\n[Thành công] Nội dung của Index CSV:")
    display(id_map_df.head(10))
    print(f"\\nTổng cộng số dòng CSV tạo ra là {len(id_map_df)}")

except Exception as e:
    print(f"Lỗi xảy ra trong quá trình sinh CSV độc lập: {e}")

Tiến hành chạy hàm vét CSV Index từ Parquet gốc...
Building index CSV directly from /content/drive/My Drive/Thesis/book_recsys/data/processed_2/books_cleaned.parquet...
Successfully generated /content/drive/My Drive/Thesis/book_recsys/data/processed_2/model_v1/cb_sbert_book_index.csv with 1173713 records.
\n[Thành công] Nội dung của Index CSV:

   row_idx   book_id
0        0   7327624
1        1   6066819
2        2   6066812
3        3    287149
4        4   6066814
5        5  33394837
6        6     89373
7        7     89375
8        8     89376
9        9     89377

\nTổng cộng số dòng CSV tạo ra là 1173713

In [ ]:
# --- CELL BỔ SUNG: VÉT CỨU HỘ HOẶC BUILD ĐỘC LẬP FILE INDEX CSV ---
# Chạy cell này sẽ sử dụng hàm độc lập build_index_csv() ta vừa xây trong Class.
# Nó đọc trực tiếp từ Parquet theo đúng thứ tự mảng gốc rồi dump chốt 1 lần xuống Drive.

try:
    print("Tiến hành chạy hàm vét CSV Index từ Parquet gốc...")
    id_map_df = builder.build_index_csv()

    # In ra một số dòng để bạn check thứ tự row_idx và book_id
    print("\\n[Thành công] Nội dung của Index CSV:")
    display(id_map_df.head(10))
    print(f"\\nTổng cộng số dòng CSV tạo ra là {len(id_map_df)}")

except Exception as e:
    print(f"Lỗi xảy ra trong quá trình sinh CSV độc lập: {e}")

Tiến hành chạy hàm vét CSV Index từ Parquet gốc...
Building index CSV directly from /content/drive/My Drive/Thesis/book_recsys/data/processed_2/books_filtered.parquet...
Successfully generated /content/drive/My Drive/Thesis/book_recsys/data/processed_2/model_v1/cb_sbert_book_index.csv with 1173713 records.
\n[Thành công] Nội dung của Index CSV:

   row_idx   book_id
0        0   7327624
1        1   6066819
2        2   6066812
3        3    287149
4        4   6066814
5        5  33394837
6        6     89373
7        7     89375
8        8     89376
9        9     89377

\nTổng cộng số dòng CSV tạo ra là 1173713

In [6]:
FaissBuilder.build_ivf_inner_product_index(matrix_path=OUTPUT_MATRIX,output_index_path=f'{_OUTDIR}/cb_sbert_matrix_v2.index')

Loading matrix from /content/drive/My Drive/Thesis/book_recsys/data/processed_2/model_v1/cb_sbert_matrix_v2.npy...
Matrix loaded. Shape: (1,173,713, 384). Calculated nlist: 4333
Initializing IndexFlatIP as the base quantizer...
Initializing IndexIVFFlat structure...
Training the K-Means clustering (This may take a moment)...
Adding vectors to the trained index...
Saving the finalized index to /content/drive/My Drive/Thesis/book_recsys/data/processed_2/model_v1//cb_sbert_matrix_v2.index...
[Success] IVF Index successfully built and saved.